# Generated by Django 3.0.6 on 2020-06-01 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pradip', '0002_album_gallery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='name',
            new_name='gname',
        ),
    ]
