# Generated by Django 3.0.6 on 2020-06-01 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pradip', '0006_auto_20200601_2336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='gname',
        ),
        migrations.AddField(
            model_name='gallery',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='album', to='pradip.Album'),
        ),
    ]
