# Generated by Django 3.0.6 on 2020-06-01 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pradip', '0007_auto_20200601_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='slug',
            field=models.SlugField(max_length=200, null=True, unique=True),
        ),
    ]
