# Generated by Django 3.0.6 on 2020-06-01 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pradip', '0008_gallery_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='slug',
        ),
    ]
